# Stage 1: Install Dependencies
FROM node:lts AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

#stage 2: Final image
FROM node:lts-bookworm-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app ./

EXPOSE 4000

CMD ["npm", "run", "dev"]
